import {useMemo,useState} from 'react';
import {BETA,buildBetaSheet,betaAngles,sheetHydrogenBonds,residueLabel,type SheetType} from '../geometry/betaSheet';
import {classifyInteractions} from '../geometry/sterics';
import {omega} from '../geometry/peptide';
import {SheetViewer,type SheetOptions,type SheetCamera} from '../components/SheetViewer';
import {RamachandranPlot} from '../components/RamachandranPlot';
const defaults:SheetOptions={backbone:true,sidechains:true,atoms:true,hbonds:true,direction:true};
const toggles:[keyof SheetOptions,string][]=[['backbone','Backbone'],['sidechains','Side chains'],['atoms','Atoms'],['hbonds','Show H-bonds'],['direction','Strand direction']];
const models={antiparallel:buildBetaSheet('antiparallel'),parallel:buildBetaSheet('parallel')};
const networks={antiparallel:sheetHydrogenBonds(models.antiparallel),parallel:sheetHydrogenBonds(models.parallel)};
const audits={antiparallel:classifyInteractions(models.antiparallel),parallel:classifyInteractions(models.parallel)};
export function BetaSheetLab(){
 const [type,setType]=useState<SheetType>('antiparallel'),[options,setOptions]=useState(defaults),[strand,setStrand]=useState(0),[residue,setResidue]=useState(4),[focus,setFocus]=useState(0),[camera,setCamera]=useState<SheetCamera>({view:'side',token:0});
 const model=models[type],bonds=networks[type],audit=audits[type],actual=betaAngles(model,strand,residue),selected=strand*BETA.stride+residue,bond=bonds[focus];
 const inspection=useMemo(()=>({selected,focus,hbonds:bonds,showBonds:options.hbonds,showDirection:options.direction}),[selected,focus,bonds,options.hbonds,options.direction]);
 const changeCamera=(view:SheetCamera['view'])=>setCamera(c=>({view,token:c.token+1}));
 const switchType=(next:SheetType)=>{setType(next);setFocus(0);};
 return <main className="helix-lab beta-lab" data-sheet-type={type}><section className="module-heading"><div><p className="eyebrow">CHAPTER 2 · FROM SEQUENCE TO STRUCTURE</p><h2>β-Sheet Lab</h2><p>Extended β-strand에서 이웃 strand 사이의 수소결합으로.</p></div><span className="model-tag">3 × Ac–(L-Ala)₇–NHMe<strong>Idealized poly-L-alanine β-sheet</strong></span></section>
 <div className="presets" role="group" aria-label="Sheet arrangement">{(['antiparallel','parallel'] as const).map(t=><button key={t} aria-pressed={type===t} onClick={()=>switchType(t)}>{t==='antiparallel'?'Antiparallel':'Parallel'}</button>)}<span>N → C 방향: {type==='antiparallel'?'→  ←  →':'→  →  →'}</span></div>
 <div className="lab-grid helix-grid"><section className="viewer-panel" aria-label="3D beta sheet"><div className="panel-heading"><h3>{type==='antiparallel'?'Antiparallel':'Parallel'} β-sheet</h3><span className="badge">3 STRANDS · 21 ALA</span></div><div className="camera-presets">{([['side','Sheet view'],['top','Top view'],['edge','Edge view'],['reset','Reset camera'],['fit','Fit structure']] as const).map(([v,label])=><button key={v} onClick={()=>changeCamera(v)}>{label}</button>)}</div>
 <SheetViewer model={model} options={options} inspection={inspection} camera={camera}/><div className="viewer-footer"><span>드래그 회전 · 휠 확대 · 방향키 / + −</span><span className="central-key">금색 = 선택 residue / H-bond focus</span></div><div className="legend"><span><i className="carbon"/>C</span><span><i className="nitrogen"/>N</span><span><i className="oxygen"/>O</span><span><i className="hydrogen"/>H (amide)</span><span className="phi-key">┄ backbone H-bond</span><span>⇢ N→C 기하학적 안내선</span></div><div className="helix-tip">{camera.view==='edge'?'Edge view · Cα–Cβ를 따라 Ala methyl기가 sheet 양쪽으로 번갈아 돌출되는지 관찰하세요.':'Top view로 N→C 방향과 C=O ··· H–N 연결을 비교하고, Edge view로 side-chain 교대 방향을 확인하세요.'}</div></section>
 <aside className="plot-panel helix-inspection"><div className="panel-heading"><h3>Backbone geometry</h3><span className="badge">MEASURED</span></div><label className="residue-select">Inspect strand <select aria-label="Inspect strand" value={strand} onChange={e=>setStrand(Number(e.target.value))}>{[0,1,2].map(s=><option key={s} value={s}>Strand {'ABC'[s]}</option>)}</select></label><label className="residue-select">Inspect residue <select aria-label="Inspect residue" value={residue} onChange={e=>setResidue(Number(e.target.value))}>{[2,3,4,5,6].map(r=><option key={r} value={r}>Ala {r}</option>)}</select></label><div className="coordinate" data-testid="sheet-measured">φ {actual.phi.toFixed(1)}° <span>/</span> ψ {actual.psi.toFixed(2)}°</div><p className="small">{residueLabel(selected)} 실제 좌표 · ω {Math.abs(omega(model,selected)).toFixed(1)}° trans</p><p className="small">Representative β-region · 고정된 보편값이 아닙니다.</p><RamachandranPlot {...actual}/>
 <div className="hbond-inspection"><h3>Focus H-bond <span className="badge" data-testid="sheet-hbond-count">{options.hbonds?bonds.length:0} / {bonds.length} 표시</span></h3><label>Backbone pair <select aria-label="Focus H-bond" value={focus} onChange={e=>{setFocus(Number(e.target.value));setOptions(o=>({...o,hbonds:true,backbone:true,atoms:true}));}}>{bonds.map((b,i)=><option key={b.o+b.h} value={i}>{residueLabel(b.acceptor)} O ··· {residueLabel(b.donor)} H</option>)}</select></label>{bond&&<p data-testid="sheet-hbond-detail"><strong>Acceptor</strong> {residueLabel(bond.acceptor)} C=O<br/><strong>Donor</strong> {residueLabel(bond.donor)} N–H<br/>H···O {bond.ho.toFixed(3)} Å · N···O {bond.on.toFixed(3)} Å<br/>N–H···O {bond.angle.toFixed(1)}°</p>}<p className="small">거리와 각도를 통과한 실제 backbone 원자쌍만 표시합니다. Cap 관련 H-bond는 표시 개수에서 제외합니다.</p></div></aside></div>
 <section className="controls" aria-label="Beta sheet display controls"><fieldset><legend>표시 옵션</legend><div className="toggles">{toggles.map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={()=>setOptions(o=>({...o,[key]:!o[key]}))}/>{label}</label>)}</div></fieldset><div className="presets"><button onClick={()=>{setType('antiparallel');setOptions(defaults);setStrand(0);setResidue(4);setFocus(0);changeCamera('reset');}}>전체 초기화</button></div></section>
 <section className="teaching"><div><h3>01 · β-strand ≠ β-sheet</h3><p>β-strand는 하나의 extended backbone segment입니다. β-sheet는 둘 이상의 β-strand가 backbone H-bond network로 배열된 구조입니다.</p></div><div><h3>02 · N → C 방향으로 구분</h3><p>Parallel은 이웃 strand가 같은 방향, antiparallel은 반대 방향입니다. 두 배열 모두 실제 단백질에 존재하며 어느 한쪽이 항상 더 안정하다는 뜻은 아닙니다.</p></div><div><h3>03 · Side chains alternate</h3><p>β-strand의 Ala methyl side chain은 backbone 양쪽 면으로 번갈아 돌출됩니다. 방향 화살표는 원자나 결합이 아닌 기하학적 안내선입니다.</p></div></section>
 <section className="helix-notes"><p>α-Helix: 한 나선 구간 안의 대표 i → i+4 H-bond. β-Sheet: 이웃 β-strand의 backbone C=O와 N–H 사이 H-bond. Side-chain H-bond를 나타내는 선이 아닙니다.</p><p>하나의 polypeptide chain 안에서 서로 떨어진 segment들이 β-sheet를 만들 수도 있습니다. 이 모델은 학습 편의를 위해 세 개의 독립된 capped strand로 표현합니다.</p><p>실제 단백질의 β-sheet는 일반적으로 완전히 평평하지 않고 twist를 보일 수 있습니다.</p><p>이 모델은 untwisted pleated sheet입니다. 실제 φ/ψ는 sequence와 주변 구조에 따라 분포를 가집니다. Peptide Geometry의 β-like −135°/+135°와 같은 β-region을 사용하며, 여기서는 φ −135° / ψ +132.27°를 선택했습니다.</p><details><summary>모델 검증과 단순화 보기</summary><p data-testid="sheet-clashes">심한 불리한 입체 충돌: {audit.seriousClashes.length}쌍 · 전체 유효 H-bond: {audit.hydrogenBonds.length}쌍 · Ala-only 표시 network: {bonds.length}쌍.</p><p>기존 판정 유지: H···O 1.5–2.6 Å, N···O 2.5–3.5 Å, N–H···O ≥120°. Amide donor와 carbonyl acceptor의 결합 관계를 확인합니다. 1–2/1–3/1–4 제외, overlap &gt;0.40 Å를 검사하며 유효 H-bond는 불리한 충돌로 중복 집계하지 않습니다.</p><p>중성 Ac/NHMe cap과 명시적 amide H를 포함합니다. 탄소 결합 H는 생략합니다. 고정 결합 geometry를 사용한 교육 모델이며 실험 구조, 에너지 계산, molecular dynamics 또는 folding simulation이 아닙니다.</p></details></section></main>;
}
