import type {Vec} from '../geometry/vector';
import type {AssemblySceneModel} from '../rendering/AssemblyScene';
import {inferBonds} from './exposure';
import {parseMultiChainPdb,parsePdbHeader,residueKey,type MultiChainStructure,type PdbHeader} from './pdb';
import {associateHetero,buildAssembly,explodedOffsets,interfaceContacts,nearestPolymerLigand,pairBetween,type HeteroAssociation,type InterfaceAnalysis,type MetalLigand} from './quaternary';

/** RCSB entry 2DN2 (Park, Yokoyama, Shibayama, Shiro & Tame 2006), human deoxyhemoglobin A, X-ray diffraction. */
export const HEMOGLOBIN_SOURCE={pdbId:'2DN2',protein:'Hemoglobin A (adult human)',organism:'Homo sapiens',method:'X-ray diffraction',resolution:1.25,
 state:'deoxy (no O₂ ligand)',doi:'10.1016/j.jmb.2006.05.036',citation:'Park et al. (2006) J. Mol. Biol. 360:690–701',sha256:'cc2fca4182e61cb85c2b0082c80167eb7d189a84b148faaa6eb810977c64e214'} as const;

export type GlobinType='alpha'|'beta';
/**
 * Globin type from the reference sequence the depositors cross-referenced (DBREF → UniProt), not from chain letters.
 * Only these two accessions are accepted; any other chain makes the analysis fail loudly.
 */
export const GLOBIN_BY_UNIPROT:Record<string,{type:GlobinType;entry:string}>={
 P69905:{type:'alpha',entry:'HBA_HUMAN'},
 P68871:{type:'beta',entry:'HBB_HUMAN'},
};
export const GLOBIN_INFO:Record<GlobinType,{symbol:string;name:string}>={alpha:{symbol:'α',name:'α-globin'},beta:{symbol:'β',name:'β-globin'}};

export type SubunitLabel='α1'|'β1'|'α2'|'β2';
export const SUBUNIT_ORDER:SubunitLabel[]=['α1','β1','α2','β2'];
/** By subunit: four distinct hues. By chain type: one hue per globin type. Heme keeps its own colors in every mode. */
export const SUBUNIT_COLORS:Record<SubunitLabel,{color:number;css:string}>={
 'α1':{color:0x3567c4,css:'#3567c4'},'β1':{color:0x3c9a55,css:'#3c9a55'},'α2':{color:0x8a5ac2,css:'#8a5ac2'},'β2':{color:0xc68416,css:'#c68416'},
};
export const TYPE_COLORS:Record<GlobinType,{color:number;css:string}>={alpha:{color:0x3f73c9,css:'#3f73c9'},beta:{color:0x3a9a58,css:'#3a9a58'}};
export const HEME_COLORS={carbon:0xc22f3c,css:'#c22f3c',iron:0xf08a1c,ironCss:'#f08a1c'} as const;

export type HemeSite={
 /** 1…4 in subunit order (α1, β1, α2, β2). */ number:number;
 group:number;resName:string;resSeq:number;fileChain:string;atomCount:number;
 iron:number;association:HeteroAssociation;
 /** Nearest polymer N/O/S to Fe, measured. */ proximal:MetalLigand&{resName:string;resSeq:number;atomName:string;chain:string};
};
export type Subunit={
 label:SubunitLabel;
 /** Assembly chain ID: the PDB chain ID, or `A_2` for the copy of PDB chain A generated by BIOMT operator 2. */ chain:string;
 sourceChain:string;operator:number;type:GlobinType;uniprot:string;entry:string;molecule:string;
 /** SEQRES length (deposited sequence). */ sequenceLength:number;
 /** Residues with coordinates. */ modeledResidues:number;
 firstResSeq:number;lastResSeq:number;residues:number[];heme:HemeSite;
};
export type HemoglobinModel={
 structure:MultiChainStructure;header:PdbHeader;bonds:[number,number][];hemeBonds:[number,number][];
 subunits:Subunit[];hemes:HemeSite[];interfaces:InterfaceAnalysis;
 assembly:{id:number;author:string;software:string;chains:string[];identity:boolean};
 /** Chain → display offset for the explanatory exploded view. */ exploded:Record<string,Vec>;
 /** Hetero group index → owning chain (spatial association). */ hetero:Record<number,string>;
 /** Number of BIOMT operators used to build the assembly (1 = deposited chains only). */ operators:number;
 /** Deposited heme ligands (only resNames declared as 'ligand'), each assigned to its nearest heme Fe. */ ligands:HemeLigand[];
 /** Other declared hetero groups, kept out of the display (e.g. crystallisation additives). */ additives:{group:number;resName:string;chain:string;resSeq:number;atoms:number}[];
};
export type HemeLigand={group:number;resName:string;chain:string;resSeq:number;
 /** Heme group index. */ heme:number;atoms:number[];
 /** Ligand atom nearest Fe and its distance (Å). */ feAtom:number;feDistance:number;occupancy:number;altlocs:number};
/** Hetero groups other than HEM must be declared: 'ligand' = bound to a heme Fe (checked); 'additive' = present but not displayed. */
export type HemoglobinOptions={hetero?:Record<string,'ligand'|'additive'>};
/** Largest accepted Fe–ligand atom distance when assigning a declared ligand to a heme (Å). */
export const FE_LIGAND_MAX=2.5;
export const EXPLODED_DISTANCE=8;

const same=(a:string[],b:string[])=>a.length===b.length&&a.every((x,i)=>x===b[i]);
const isIdentity=(op:{rotation:number[][];translation:number[]})=>op.rotation.every((row,i)=>row.every((v,j)=>v===(i===j?1:0)))&&op.translation.every(v=>v===0);
function fail(message:string):never{throw new Error(`Hemoglobin validation: ${message}`);}

/**
 * Builds the teaching model from the deposited file and verifies every claim the module makes:
 * one biological assembly = the deposited chains under the identity operator; two α and two β chains by DBREF
 * accession with identical SEQRES within each type; one heme per chain by spatial association; Fe with a measured
 * polymer ligand. Labels: α1 = first α chain in the file; β1 = the β chain with the larger α1 contact (the α1β1
 * packing interface); α2 and β2 = the remaining chains.
 */
export function analyzeHemoglobin(text:string,options:HemoglobinOptions={}):HemoglobinModel{
 const deposited=parseMultiChainPdb(text),header=parsePdbHeader(text),heteroRoles=options.hetero??{};
 if(header.assemblies.length!==1)fail(`expected one biological assembly, found ${header.assemblies.length}`);
 const bio=header.assemblies[0],identity=bio.operators.length===1&&isIdentity(bio.operators[0]);
 if(!same([...bio.chains].sort(),[...deposited.chains].sort()))fail('assembly chains are not the deposited polymer chains');
 if(!identity&&!isIdentity(bio.operators[0]))fail('first assembly operator is not the identity');
 // Identity-only assembly: the deposited structure itself. Otherwise the BIOMT operators generate rigid copies.
 const built=identity?{structure:deposited,copies:deposited.chains.map(chain=>({chain,source:chain,operator:1}))}:buildAssembly(deposited,bio.chains,bio.operators);
 const structure=built.structure,sourceOf=(chain:string)=>built.copies.find(c=>c.chain===chain)!.source;
 const types=new Map<string,{type:GlobinType;uniprot:string;entry:string}>();
 for(const chain of structure.chains){
  const refs=header.dbref.filter(d=>d.chain===sourceOf(chain)&&d.database==='UNP');
  if(refs.length!==1)fail(`chain ${chain} needs exactly one UniProt DBREF`);
  const globin=GLOBIN_BY_UNIPROT[refs[0].accession];
  if(!globin||globin.entry!==refs[0].idCode)fail(`chain ${chain} is ${refs[0].accession} ${refs[0].idCode}, not a human α/β globin`);
  types.set(chain,{type:globin.type,uniprot:refs[0].accession,entry:refs[0].idCode});
 }
 const chainsOf=(t:GlobinType)=>structure.chains.filter(c=>types.get(c)!.type===t),alphas=chainsOf('alpha'),betas=chainsOf('beta');
 if(alphas.length!==2||betas.length!==2)fail(`expected α2β2, found α${alphas.length}β${betas.length}`);
 const seqOf=(chain:string)=>header.seqres.get(sourceOf(chain))!;
 for(const group of [alphas,betas])if(!same(seqOf(group[0]),seqOf(group[1])))fail(`chains ${group.join('/')} differ in sequence`);
 if(same(seqOf(alphas[0]),seqOf(betas[0])))fail('α and β sequences are identical');
 for(const chain of structure.chains){
  // Each modeled residue must be the SEQRES residue at its position (DBREF gives the first residue number), so gaps are allowed but shifts are not.
  const seq=seqOf(chain),begin=header.dbref.find(d=>d.chain===sourceOf(chain)&&d.database==='UNP')!.seqBegin;
  if(structure.residues.some(r=>r.chain===chain&&(r.insertionCode!==''||seq[r.resSeq-begin]!==r.resName)))fail(`chain ${chain} modeled residues do not follow SEQRES`);
 }
 const interfaces=interfaceContacts(structure);
 const contactSize=(a:string,b:string)=>{const p=pairBetween(interfaces,a,b);return p?p.residues[0].length+p.residues[1].length:0;};
 const alpha1=alphas[0],alpha2=alphas[1],beta1=[...betas].sort((a,b)=>contactSize(alpha1,b)-contactSize(alpha1,a))[0],beta2=betas.find(c=>c!==beta1)!;
 if(contactSize(alpha1,beta1)===contactSize(alpha1,beta2))fail('α1 contacts both β chains equally; α1β1 is ambiguous');
 const labelOf:Record<string,SubunitLabel>={[alpha1]:'α1',[beta1]:'β1',[alpha2]:'α2',[beta2]:'β2'};

 const hemeGroups=structure.hetero.filter(g=>g.resName==='HEM');
 const unexpected=structure.hetero.filter(g=>g.resName!=='HEM'&&!heteroRoles[g.resName]);
 if(unexpected.length)fail(`unexpected hetero groups ${unexpected.map(residueKey).join(', ')}`);
 const hemeSites=hemeGroups.map(group=>{
  const irons=group.atoms.filter(i=>structure.atoms[i].element==='FE');
  if(irons.length!==1)fail(`${residueKey(group)} has ${irons.length} Fe atoms`);
  const association=associateHetero(structure,group),ligand=nearestPolymerLigand(structure,irons[0]),res=structure.residues[ligand.residue],atom=structure.atoms[ligand.atom];
  return {group:group.index,resName:group.resName,resSeq:group.resSeq,fileChain:group.chain,atomCount:group.atoms.length,iron:irons[0],association,
   proximal:{...ligand,resName:res.resName,resSeq:res.resSeq,atomName:atom.name,chain:res.chain},number:0};
 });
 for(const chain of structure.chains){const n=hemeSites.filter(h=>h.association.chain===chain).length;if(n!==1)fail(`chain ${chain} is associated with ${n} hemes`);}
 // Heme ligands (e.g. O₂): assigned to the heme whose Fe is nearest, from coordinates; must be within FE_LIGAND_MAX of that Fe.
 const ligands:HemeLigand[]=structure.hetero.filter(g=>heteroRoles[g.resName]==='ligand').map(g=>{
  let best:{site:(typeof hemeSites)[number];atom:number;distance:number}|null=null;
  for(const site of hemeSites)for(const a of g.atoms){const d=Math.hypot(...structure.atoms[a].position.map((v,k)=>v-structure.atoms[site.iron].position[k]));if(!best||d<best.distance)best={site,atom:a,distance:d};}
  if(!best||best.distance>FE_LIGAND_MAX)fail(`${residueKey(g)} is not bound to a heme Fe`);
  return {group:g.index,resName:g.resName,chain:g.chain,resSeq:g.resSeq,heme:best.site.group,atoms:g.atoms,feAtom:best.atom,feDistance:best.distance,
   occupancy:Math.min(...g.atoms.map(a=>structure.atoms[a].occupancy)),altlocs:g.atoms.filter(a=>structure.atoms[a].altLoc!=='').length};
 });
 const subunits=structure.chains.map(chain=>{
  const residues=structure.residues.filter(r=>r.chain===chain),t=types.get(chain)!,heme=hemeSites.find(h=>h.association.chain===chain)!,copy=built.copies.find(c=>c.chain===chain)!;
  return {label:labelOf[chain],chain,sourceChain:copy.source,operator:copy.operator,type:t.type,uniprot:t.uniprot,entry:t.entry,molecule:header.molecules.find(m=>m.chains.includes(copy.source))?.name??'',
   sequenceLength:seqOf(chain).length,modeledResidues:residues.length,firstResSeq:residues[0].resSeq,lastResSeq:residues.at(-1)!.resSeq,residues:residues.map(r=>r.index),heme} satisfies Subunit;
 }).sort((a,b)=>SUBUNIT_ORDER.indexOf(a.label)-SUBUNIT_ORDER.indexOf(b.label));
 subunits.forEach((s,i)=>{s.heme.number=i+1;});
 const hemes=subunits.map(s=>s.heme);
 const others=structure.hetero.filter(g=>heteroRoles[g.resName]==='additive').map(g=>({group:g.index,resName:g.resName,chain:g.chain,resSeq:g.resSeq,atoms:g.atoms.length}));
 return {structure,header,bonds:inferBonds(structure),hemeBonds:inferBonds({atoms:structure.atoms,residues:structure.hetero.filter(g=>g.resName==='HEM')}),subunits,hemes,interfaces,
  assembly:{id:bio.id,author:bio.author,software:bio.software,chains:bio.chains,identity},exploded:explodedOffsets(structure,EXPLODED_DISTANCE),
  hetero:Object.fromEntries(hemes.map(h=>[h.group,h.association.chain])),operators:bio.operators.length,ligands,additives:others};
}

export const residueLabel=(r:{resName:string;resSeq:number;insertionCode:string})=>`${r.resName[0]}${r.resName.slice(1).toLowerCase()} ${r.resSeq}${r.insertionCode}`;

/** Scene input: PDB chain → educational label and colors; heme → spatially associated chain, Fe and proximal ligand. */
export const hemoglobinSceneModel=(m:HemoglobinModel):AssemblySceneModel=>({
 structure:m.structure,bonds:m.bonds,hemeBonds:m.hemeBonds,exploded:m.exploded,
 chains:m.subunits.map(s=>({chain:s.chain,label:s.label,color:SUBUNIT_COLORS[s.label].color,typeColor:TYPE_COLORS[s.type].color})),
 hemes:m.hemes.map(h=>({group:h.group,chain:h.association.chain,iron:h.iron,number:h.number,proximal:{residue:h.proximal.residue,atom:h.proximal.atom}})),
});

